title: "Rather Be Exploring"
description: "Planes, trains, and the places they take us."

url: "https://ratherbeexploring.github.io"
baseurl: # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about


google_analytics: "10623241786"
